Feat/refactor html style
Aierbote/registro-di-classe pull request #28
Opened 2023-12-18 11:57 UTC by RitaCaterina

after prettier corrected i remove style in line and used semantics tags

2023-12-18 12:03 UTC, Aierbote reviewed
It's not ripe enough yet. Good work so far, I'll take it from here!

2023-12-19 22:23 UTC, Aierbote requested changes
There is still alot to do

2024-01-02 16:01 UTC, Rizaaal submitted a review, later dismissed
The CSS is incomplete, but commit is merged anyways as we need the html to start working on frontend JS logic

2024-01-02 16:55 UTC, Aierbote approved these changes

2024-01-02 17:27 UTC, Rizaaal approved these changes

2024-01-02 17:27 UTC, merged